spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lg://employee-service
          predicates:
            - Path=/employee/**
        - id: department-service
          uri: lg://department-service
          predicates:
            - Path=/departments/**