server:
  port: 8081

spring:
  application:
    name: department-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defalultZone: http://localhost:8761/eureka/