spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_service
    username: shrikant
    password: Kale@333
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: inventory-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0
# Sleuth + Zipkin
  zipkin:
    baseUrl: https://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0