spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761

# Sleuth + Zipkin
  zipkin:
    baseUrl: https://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0