spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: product-service
        uri: lb://product-service
      routes[1]:
        id: order-service
        uri: lb://order-service
      routes[2]:
        id: discovery-server
        uri: http://localhost:8761
        predicates: Path=/eureka/web
        filters: SetPath=/
      routes[3]:
        id: discovery-server-static
        uri: http://localhost:8761
        predicates: Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8888
# Sleuth + Zipkin
  zipkin:
    baseUrl: https://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0