spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: shrikant
    password: Kale@333
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service
server:
  port: 8081